USE MOVIES 
GO

--LIST OF OBJECT IN A DATABASE
SELECT * FROM sys.objects

--LIST OF TABLES IN A DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES

--LIST OF ALL COLUMNS WITH RESPECTIVE TABLES IN A DATABASE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

--EXPLORE A PARTICULAR TABLE
SP_HELP 'tblStudio'
GO

--LIST OF ALL HEADERS
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE 1=2

-- COPY WITH HEADERS
-- TABLE_CATALOG	TABLE_SCHEMA	TABLE_NAME	COLUMN_NAME	ORDINAL_POSITION	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	CHARACTER_SET_CATALOG	CHARACTER_SET_SCHEMA	CHARACTER_SET_NAME	COLLATION_CATALOG	COLLATION_SCHEMA	COLLATION_NAME	DOMAIN_CATALOG	DOMAIN_SCHEMA	DOMAIN_NAME


--DIMENSION TABLES
SELECT * FROM [dbo].[tblLanguage]
SELECT * FROM [dbo].[tblStudio]
SELECT * FROM [dbo].[tblCountry]
SELECT * FROM [dbo].[tblCertificate]
SELECT * FROM [dbo].[tblActor]
SELECT * FROM [dbo].[tblCast]
SELECT * FROM [dbo].[tblDirector]

--FACT TABLES
SELECT * FROM [dbo].[tblFilm]


-- CTRL + N = New Query
-- CTRL + R = Remove results window temporarily
-- F5 Runs the Query

