/* SOURCE:
https://www.youtube.com/watch?v=Q7pngYFaFC0&list=PLd3UqWTnYXOkDmQvCVKsXeoGeocusMP4i&index=46
https://www.youtube.com/watch?v=G1a1TnGzXBc&list=PLd3UqWTnYXOkDmQvCVKsXeoGeocusMP4i&index=47
https://www.youtube.com/watch?v=jFl7ZCPhvg4&list=PLd3UqWTnYXOkDmQvCVKsXeoGeocusMP4i&index=48
*/

USE MOVIES

GO

/*

-- VIEWS - IS A VIRTUAL TABLE / IMAGINARY TABLE.
-- IT IS USED TO ENFORCE DATA SECURITY BY SELECTIVELY HIDING COLUMNS IN A TABLE



*/

-- CREATE VIEW

SELECT * FROM [dbo].[tblActor]
--ASUMING WE WANT TO HIDE DOB FROM ALL USERS
--DBA CAN RESTRICT ACCESS TO [dbo].[tblActor] AND GRANT ACCESS TO VIEW V_ACTOR

CREATE VIEW V_ACTOR
AS
SELECT [ActorID],[ActorName],[ActorGender] FROM [dbo].[tblActor]


--NOW USER CAN USE THE VIEW:
SELECT * FROM V_ACTOR

-- ENCRYPTION

-- ASSUMING USER IS SMART AND WANTS TO STEAL A WAY TO SEE DOB
SP_HELPTEXT V_ACTOR --INBUILT STORED PROCEDURE

-- NOW USER KNOWS BASE TABLE 
SELECT * FROM [dbo].[tblActor]

--HOW TO OVERCOME? -- WITH ENCRYPTION

-- IN A NEW VIEW

CREATE VIEW V_ACTOR_E WITH ENCRYPTION
AS
SELECT [ActorID],[ActorName],[ActorGender] FROM [dbo].[tblActor]

SELECT * FROM V_ACTOR_E

SP_HELPTEXT V_ACTOR_E -- SEE ENCRYPTED

-- IN AN EXISTING VIEW

ALTER VIEW V_ACTOR
WITH ENCRYPTION
AS
SELECT [ActorID],[ActorName],[ActorGender] FROM [dbo].[tblActor]
GO

SELECT * FROM V_ACTOR

SP_HELPTEXT V_ACTOR --SEE ENCRPTED NOW


--SCHEMABINDING

-- IN REAL WORLD SCENARIO, WHAT IF SOMEONE DELETES BASE TABLE [dbo].[tblActor]?
-- VIEW WILL BE INVALID
-- IN ORDER TO OVERCOME, WE DO "SCHEMABINDING"

-- IN A NEW VIEW

CREATE VIEW V_ACTOR_S WITH SCHEMABINDING
AS
SELECT [ActorID],[ActorName],[ActorGender] FROM [dbo].[tblActor]

SELECT * FROM V_ACTOR_S

--FOR DELETING A RECORD - USE DELETE
-- FOR DELETING ENTIRE TABLE, USE DROP

DROP TABLE [dbo].[tblActor] -- WE CANNOT DELETE BASE TABLE (OBSERVE ERROR)


-- TYPES OF VIEWS

-- A.) SIMPLE VIEW - VIEW ON A SINGLE TABLE IS A SIMPLE VIEW

-- ALL EXAMPLES DONE ABOVE ARE SIMPLE VIEW
-- ANY INSERT / UPDATE / DELETE OPERATION IN BASE TABLE REFLECTS IN THE VIEW OR VICE VERSA.
-- IT IS ALSO CALLED UPDATABLE VIEW

-- B.) COMPLEX VIEW
-- A VIEW DEFINED ON 2 MORE TABLES
-- NON UPDATABLE / READ ONLY VIEWS
--CANNOT RUN DML OPERATIONS

CREATE VIEW FILM_COMPLEX
AS
SELECT * FROM [dbo].[tblFilm] AS F
INNER JOIN
[dbo].[tblCountry] AS C
ON
F.FilmCountryID=C.CountryID

SELECT * FROM FILM_COMPLEX

DELETE FROM FILM_COMPLEX
WHERE [FilmID] = 260 -- OBSERVE ERROR

-- THESE ARE NON-UPDATABLE VIEWS


-- CHECK OPTION
SELECT * FROM [dbo].[tblLanguage]

CREATE VIEW V_LANG
AS
SELECT * FROM [dbo].[tblLanguage]
WHERE [LanguageName]='ENGLISH'

SELECT * FROM V_LANG

INSERT INTO V_LANG ([LanguageID],[LanguageName])
VALUES (12,'ENGLISH')

INSERT INTO V_LANG ([LanguageID],[LanguageName])
VALUES (13,'ENGLISH')

SELECT * FROM V_LANG

INSERT INTO V_LANG ([LanguageID],[LanguageName])
VALUES (14,'URDU')

-- LOGICALLY, WE SHOULD CHECKED BY SQL TO NOT ENTER 'URDU'

SELECT * FROM V_LANG
SELECT * FROM [dbo].[tblLanguage]

-- HOW TO ENABLE THIS?

ALTER VIEW V_LANG
AS
SELECT * FROM [dbo].[tblLanguage]
WHERE [LanguageName]='ENGLISH'
WITH CHECK OPTION

INSERT INTO V_LANG ([LanguageID],[LanguageName])
VALUES (15,'PUNJABI') -- SEE THE ERROR


-- DELETING A VIEW

DROP VIEW <VIEW NAME>

