USE MOVIES
GO

--STORED PROCEDURE

--CREATE SP
CREATE PROC MYPROCEDURE_1
AS
SELECT * FROM [dbo].[tblFilm]
GO

--RUN SP
EXEC  MYPROCEDURE_1

-- ALTER SP
ALTER PROC MYPROCEDURE_1
AS
SELECT * FROM [dbo].[tblCountry]
GO

--RUN SP
EXEC  MYPROCEDURE_1

--TO GET CODE OF A SP
SP_HELPTEXT 'MYPROCEDURE_1'

--DROP SP
DROP PROC MYPROCEDURE_1

--RE-CREATE SP
CREATE PROC MYPROCEDURE_1
AS
SELECT * FROM [dbo].[tblFilm]
GO

--RUN SP
EXEC  MYPROCEDURE_1

--ALTER SP

ALTER PROC MYPROCEDURE_1
AS
SELECT * FROM [dbo].[tblCountry]
GO

--RUN SP
EXEC  MYPROCEDURE_1



--INPUT PARAMETERS IN A SP

CREATE PROCEDURE MYPROCEDURE_2
@MYVAR1 INT,
@MYVAR2 INT
AS
SELECT (@MYVAR1-@MYVAR2)*10

GO

EXEC  MYPROCEDURE_2 12,10
EXEC MYPROCEDURE_2 @MYVAR1=12,@MYVAR2=10
EXEC MYPROCEDURE_2 @MYVAR1=10,@MYVAR2=12

GO

--OUTPUT PARAMTER IN SP

CREATE PROCEDURE MYPROCEDURE_3
@MYVAR_INPUT INT,
@MYVAR_OUTPUT INT OUTPUT
AS
SET @MYVAR_OUTPUT= @MYVAR_INPUT*50

-- RUN A SP WITH OUTPUT PARAMETER

DECLARE @MYVAL INT
EXEC MYPROCEDURE_3 @MYVAR_INPUT=12,@MYVAR_OUTPUT=@MYVAL OUTPUT
SELECT @MYVAL AS VALUE




---


CREATE TABLE STUDENT (ID INT IDENTITY PRIMARY KEY,NAME VARCHAR(50)) 
GO

CREATE PROCEDURE MYPROCEDURE_4 
@NAME VARCHAR(50), 
@ID INT OUTPUT 
AS
INSERT INTO STUDENT(NAME)
VALUES(@NAME) 
SELECT @ID=SCOPE_IDENTITY() -- RETURNS LAST COUNT OF VALUE PASSED
GO 

DECLARE @IDENTITYOUTPUT INT 
EXEC MYPROCEDURE_4 @NAME='DHEERAJ', @ID=@IDENTITYOUTPUT OUTPUT 
SELECT @IDENTITYOUTPUT AS LASTIDVALUE 
GO 

DECLARE @IDENTITYOUTPUT INT 
EXEC MYPROCEDURE_4 @NAME='DHEERAJ', @ID=@IDENTITYOUTPUT OUTPUT 
SELECT @IDENTITYOUTPUT AS LASTIDVALUE 
GO 

-- IMAGINE A SCENARIO -- INCIDENT # IS AUTO GENEREATED ON A WEBSITE

CREATE PROC MYPROCEDURE_5
@name varchar(50)=null --DEFAULT VALUE
as
if @name is NULL
 begin
  print 'You must specify the name'
  return(1)
 end
insert into Student(Name) values(@name)
select Scope_Identity()
return(2)

go

-- RUN SP WITHOUT ANY NAME

declare @val int
exec @val=MYPROCEDURE_5 @name=null
select @val value
go

-- OUTPUT RETURNS 1

declare @val int
exec @val=MYPROCEDURE_5 @name='Rahul'
select @val value
go

-- FIRST OUTPUT IS Scope_Identity
-- SECOND OUTPUT RETURNS 2

SELECT * FROM STUDENT