-- https://www.youtube.com/watch?v=IIbwLr0v7LA&list=PLVlQHNRLflP8WFEvFvANnUsD2y8HJIJh1&index=46
-- https://www.youtube.com/watch?v=yK8epOlliU4&list=PLVlQHNRLflP8WFEvFvANnUsD2y8HJIJh1&index=47
-- https://www.sqlservertutorial.net/sql-server-stored-procedures/sql-server-cursor/