-- IDENTITY IN DETAIL

USE MOVIES
GO

CREATE TABLE [DEMOIDENTITYTABLE](
	[ID] [INT] IDENTITY(1,1) PRIMARY KEY,
	[NAME] [VARCHAR](50) NULL,
	[ADDRESS] [VARCHAR](50) NULL,
 )

GO


INSERT INTO  [DEMOIDENTITYTABLE] ([NAME], [ADDRESS]) VALUES ('VIKAS', '123 MN1')
INSERT INTO  [DEMOIDENTITYTABLE] ([NAME], [ADDRESS]) VALUES ('VARUN', '678 MN1')
INSERT INTO  [DEMOIDENTITYTABLE] ([NAME], [ADDRESS]) VALUES ('VIKRAM', '156 RM')
INSERT INTO  [DEMOIDENTITYTABLE] ([NAME], [ADDRESS]) VALUES ('RAHUL', '436 KM')
INSERT INTO  [DEMOIDENTITYTABLE] ([NAME], [ADDRESS]) VALUES ('SUMIT', '56 TM')


SELECT * FROM  [DEMOIDENTITYTABLE] 


-- HOW TO INSERT A ROW WITH OLD OR PREVIOUS IDENTITY VALUE WHICH 
-- WAS DELETED IN SQL SERVER TABLE



SELECT * FROM DEMOIDENTITYTABLE

INSERT INTO DEMOIDENTITYTABLE (NAME,ADDRESS) VALUES ('VIKRANT','556 RM')

SELECT * FROM DEMOIDENTITYTABLE

DELETE FROM DEMOIDENTITYTABLE WHERE ID=3

SELECT * FROM DEMOIDENTITYTABLE

SET IDENTITY_INSERT DEMOIDENTITYTABLE ON
INSERT INTO DEMOIDENTITYTABLE (ID,NAME,ADDRESS) VALUES (3,'VIKRAM','156 RM')
SET IDENTITY_INSERT DEMOIDENTITYTABLE OFF

SELECT * FROM DEMOIDENTITYTABLE


-- RESET IDENTITY

SELECT * FROM DEMOIDENTITYTABLE
GO

INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('ALICE','917 SL')
INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('BOB','987 ASL')
INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('JOHN','F7 ERF')
GO

SELECT * FROM DEMOIDENTITYTABLE

DELETE FROM DEMOIDENTITYTABLE WHERE ID>5

SELECT * FROM DEMOIDENTITYTABLE

INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('ADAM','987 SL')

SELECT * FROM DEMOIDENTITYTABLE

DELETE FROM DEMOIDENTITYTABLE WHERE ID>5

SELECT * FROM DEMOIDENTITYTABLE
GO

DBCC CHECKIDENT (DEMOIDENTITYTABLE,RESEED,5)
GO

INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('SAGAR','917 SL')
INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('SAMEER','987 ASL')
INSERT INTO DEMOIDENTITYTABLE(NAME,ADDRESS) VALUES ('SURAJ','F7 ERF')

SELECT * FROM DEMOIDENTITYTABLE


-- SEQUENCE
/*
SYNTAX:
CREATE SEQUENCE [schema].[Name_of_Sequence]
  [ AS <data type> ]
  [ START WITH <value> ]
  [ INCREMENT BY <value> ]
  [ MINVALUE <value > | NO MINVALUE ]
  [ MAXVALUE <value> | NO MAXVALUE ]
  [ CYCLE | NO CYCLE ]
  [ CACHE value | NO CACHE ];
*/


CREATE SEQUENCE [dbo].[NewCounter]
AS INT
START WITH 5
INCREMENT BY 5

SELECT NEXT VALUE FOR [dbo].[NewCounter]

-- HOW TO USE SEQUENCE:

CREATE TABLE Students
(
	Id INT PRIMARY KEY,
	StudentName VARCHAR (50),
	StudentAge INT
)

CREATE SEQUENCE [dbo].[IdCounter]
AS INT
START WITH 1
INCREMENT BY 1	

-- PUT SEQUENCE VALUE IN ID WHILE INSERT

INSERT INTO Students VALUES (NEXT VALUE FOR [dbo].[IdCounter], 'Sally', 20 )
INSERT INTO Students VALUES (NEXT VALUE FOR [dbo].[IdCounter],'Edward', 36 )
INSERT INTO Students VALUES (NEXT VALUE FOR [dbo].[IdCounter],'Jon', 35)
INSERT INTO Students VALUES (NEXT VALUE FOR [dbo].[IdCounter],'Scot', 41 )
INSERT INTO Students VALUES (NEXT VALUE FOR [dbo].[IdCounter],'Ben', 35 )


SELECT * FROM Students

-- https://www.sqlshack.com/sequence-objects-in-sql-server/

-- DIFFERENCE BETWEEN IDENTITY & SEQUENCE

-- https://www.sqlshack.com/difference-between-identity-sequence-in-sql-server/
