/* 

--COPY ENTIRE TABLE
SOURCE: https://www.w3schools.com/sql/sql_select_into.asp

--SYNTAX
SELECT *
INTO newtable [IN externaldb]
FROM oldtable
WHERE condition;

*/

SELECT * INTO DEMOFILM1 FROM [dbo].[tblFilm] WHERE [FilmCountryID]<>241


/*

TEMPORARY TABLE
SOURCE : https://www.youtube.com/watch?v=7ZyermWlVxc&list=PLd3UqWTnYXOkDmQvCVKsXeoGeocusMP4i&index=40

STORAGE LOCATION:
GOTO DATABASES --> SYSTEM DATABASES --> tempdb

TWO TYPES : LOCAL & GLOBAL

LOCAL TEMPORARY TABLE  -  # - EXISTING OR HOME SESSION
GLOBAL TEMPORARY TABLE - ## - ALL SESSION
*/


--LOCAL TEMPORARY TABLE
CREATE TABLE #MYTEMP(ID INT, NAME VARCHAR(50))
INSERT INTO #MYTEMP VALUES (10,'DT'),(20,'AT')
SELECT * FROM #MYTEMP -- THIS QUERY WILL NOT RUN IN NEW SESSION (NEW QUERY)
--WE CAN HAVE #MYTEMP WITH SAME NAME IN ANOTHER SESSION

--GLOBAL TEMPORARY TABLE
CREATE TABLE ##MYTEMP(ID INT, NAME VARCHAR(50))
INSERT INTO ##MYTEMP VALUES (10,'DT'),(20,'AT')
SELECT * FROM ##MYTEMP -- THIS QUERY WILL RUN IN NEW SESSION (NEW QUERY)
--WE CANNOT HAVE ##MYTEMP SAME NAME IN NEW SESSION (NEW QUERY)